before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
after_script: "mvn deploy --settings target/travis/settings.xml"
language: java
jdk:
 - oraclejdk8
sudo: false
script: mvn clean verify
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: pik-predator
 on:
  repo: ACharchula/PIK-predator
